In [124]:
import numpy as np

In [125]:
np.zeros(4)

array([0., 0., 0., 0.])

In [126]:
array = np.array([0,0,0,0])
def calc(array):
    if np.any(array!=0): 
        return False 
    else:
        return True
    
calc(array)

True

In [128]:
array1 = np.array([1.0,2.0,3.0])
array2 = np.array([1.0000,2.0001,3.0002])
def calc(array1,array2):
    

IndentationError: expected an indented block (1658265475.py, line 4)

In [131]:
def calc():
    np.zeros(10)
    np.ones(10)
    np.fives(10)
    
calc()

AttributeError: module 'numpy' has no attribute 'fives'

In [132]:
my_list=[0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,5,5,5,5,5,5,5,5,5,5]

In [134]:
x = np.array(my_list)

In [136]:
x

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5])

In [137]:
array=np.arange(30,71)

In [138]:
array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [139]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
np.random.rand()

0.269625206721836

In [144]:
np.random.rand(15)

array([0.83727836, 0.78583211, 0.40625713, 0.12165601, 0.67241808,
       0.60418948, 0.28855024, 0.43563327, 0.59823156, 0.26509313,
       0.3314608 , 0.18630656, 0.90825859, 0.81976706, 0.78158582])

In [148]:
vector = np.arange(16,55) 
vector

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
       33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54])

In [149]:
vector = np.random.randint(0,10,5)

In [151]:
vector

array([6, 6, 3, 0, 4])

In [198]:
matrix=np.zeros((10,10))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

In [201]:
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [203]:
matrix=np.zeros((5,5))
for i in range(5):
    matrix[i,i]=i+1

In [205]:
matrix

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [207]:
matrix=np.zeros((4,4))
for i in range(4):
    for k in range(4):
        if (i+k)%2!=0:
            matrix[i,k]=1
        

In [209]:
matrix

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [214]:
array=np.random.rand(40)

In [216]:
array

array([0.35839372, 0.00367614, 0.20177923, 0.20086451, 0.53175287,
       0.13391571, 0.95991637, 0.28909451, 0.50173428, 0.98797857,
       0.83725911, 0.4235866 , 0.19522958, 0.72124977, 0.74547126,
       0.88156411, 0.83048073, 0.34571993, 0.88258547, 0.10359685,
       0.30775954, 0.51494431, 0.99643017, 0.54207698, 0.92789268,
       0.50968851, 0.45931262, 0.23167147, 0.66615301, 0.30928934,
       0.30351234, 0.85528263, 0.37538018, 0.40562137, 0.66155695,
       0.40990206, 0.95090816, 0.81886091, 0.16151056, 0.1970652 ])

In [236]:
array =np.arange(0,10)
array2=array>3
array[array2]

array([4, 5, 6, 7, 8, 9])